### ISSUE TITLE
juniper_rocket integration is broken

### ISSUE THREAD

**Issue by lanesawyer** [graphql-rust/juniper#939]
**Describe the bug**
:wave: Hi there!

I was trying to use Juniper with a Rocket app I'm writing, but when I tried to do so, the `juniper_rocket` integration throws errors (listed below). I pulled the Juniper repo itself and tried to build the integration and it failed there as well, so as far as I can tell, the integration does not work.

```
error[E0277]: `?` couldn't convert the error to `(rocket::http::Status, std::string::String)`
   --> juniper_rocket\src\lib.rs:280:81
    |
280 |             .map_err(|e| Err((Status::InternalServerError, format!("{:?}", e))))?;
    |                                                                                 ^ the trait `std::convert::From<Result<_, (rocket::http::Status, std::string::String)>>` is not implemented for `(rocket::http::Status, std::string::String)`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = help: the following implementations were found:
              <(usize, usize) as std::convert::From<toml::tokens::Span>>
    = note: required because of the requirements on the impl of `FromResidual<Result<Infallible, Result<_, (rocket::http::Status, std::string::String)>>>` for `Outcome<GraphQLRequest<S>, (rocket::http::Status, std::string::String), rocket::Data>`
    = note: required by `from_residual`

error[E0277]: `?` couldn't convert the error to `(rocket::http::Status, std::string::String)`
   --> juniper_rocket\src\lib.rs:283:97
    |
283 |             serde_json::from_str(&body).map_err(|e| Err((Status::BadRequest, format!("{}", e))))?
    |                                                                                                 ^ the trait `std::convert::From<Result<_, (rocket::http::Status, std::string::String)>>` is not implemented for `(rocket::http::Status, std::string::String)`
    |
    = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
    = help: the following implementations were found:
              <(usize, usize) as std::convert::From<toml::tokens::Span>>
    = note: required because of the requirements on the impl of `FromResidual<Result<Infallible, Result<_, (rocket::http::Status, std::string::String)>>>` for `Outcome<GraphQLRequest<S>, (rocket::http::Status, std::string::String), rocket::Data>`
    = note: required by `from_residual`
```

**To Reproduce**
- Navigate to the `juniper_rocket` folder
- Run `cargo test` or `cargo build`
- See the errors

**Expected behavior**
I expected the Rocket integration to compile.

**Comment by LegNeato** [comment]
This looks to have been broken by https://github.com/SergioBenitez/Rocket/commit/425f741b873424046e20855f3fe13a3eb01b0c5e

**Comment by LegNeato** [comment]
More info here: https://github.com/SergioBenitez/Rocket/issues/1647

**Comment by LegNeato** [comment]
This has now been pushed to crates.io.
